[package]
name = "hydrant"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
n0-future = "0.3"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
miette = { version = "7", features = ["fancy"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rmp-serde = "1.3.1"

fjall = "3.0"
serde_ipld_dagcbor = "0.6"

url = "2.5"
smol_str = "0.3"
futures = "0.3"
reqwest = { version = "0.12", features = ["json", "rustls-tls", "stream", "gzip", "brotli", "zstd"], default-features = false }
axum = { version = "0.8.8", features = ["ws", "macros"] }
tower-http = { version = "0.6.6", features = ["cors", "trace"] }
tokio-stream = "0.1"
async-stream = "0.3"

jacquard = { git = "https://tangled.org/nonbinary.computer/jacquard", features = ["streaming"] }
jacquard-common = { git = "https://tangled.org/nonbinary.computer/jacquard" }
jacquard-api = { git = "https://tangled.org/nonbinary.computer/jacquard" }
jacquard-identity = { git = "https://tangled.org/nonbinary.computer/jacquard", features = ["dns", "cache"] }
jacquard-repo = { git = "https://tangled.org/nonbinary.computer/jacquard" }
jacquard-axum = { git = "https://tangled.org/nonbinary.computer/jacquard" }
jacquard-derive = { git = "https://tangled.org/nonbinary.computer/jacquard" }
chrono = { version = "0.4.43", features = ["serde"] }
humantime = "2.3.0"

mimalloc = { version = "0.1", features = ["v3"] }
scc = "3"
